# # # List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# # # 使用一个带有 Python 3.6 的预构建镜像
# # image:
# #        gitpod/workspace-full:latest
# # tasks:
# #   - name: "install requirements"
# #     command: |
# #       # 更新 pip
# #       pip install -U pip
# #       # 安装 pyenv 并安装 Python 3.6.9
# #       pyenv install 3.6.9
# #       # 切换到 Python 3.6.9
# #       pyenv global 3.6.9
# #       # 再次更新 pip
# #       pip install -U pip
# #       # 安装 yapf 格式化工具
# #       pip install yapf
# #       # 安装项目依赖
# #       pip install -r requirements.txt
# #       # 退出任务
# #       exit

# # vscode:
# #   extensions:
# #     - ms-python.python
# #     - esbenp.prettier-vscode
# #     - ms-toolsai.jupyter

# # List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
# # 使用一个带有 Python 3.6 的预构建镜像
# image:
#        gitpod/workspace-full:latest
# tasks:
#   - name: "install requirements"
#     command: |
#       # 更新 pip
#       pip install -U pip
#       # 安装 pyenv 并安装 Python 3.6.0
#       pyenv install 3.6.0
#       # 切换到 Python 3.6.0
#       pyenv global 3.6.0
#       # 再次更新 pip
#       pip install -U pip
#       # 安装 yapf 格式化工具
#       pip install yapf
#       # 创建并激活虚拟环境
#       python -m venv tf1_env
#       source tf1_env/bin/activate
#       # 确保虚拟环境使用正确的 Python 版本
#       pyenv local 3.6.0
#       # 安装 TensorFlow 1.x 版本
#       pip install tensorflow==1.15
#       # 安装项目依赖
#       pip install -r requirements.txt
#       # 保持虚拟环境的激活状态
#       exec $SHELL

# vscode:
#   extensions:
#     - ms-python.python
#     - esbenp.prettier-vscode
#     - ms-toolsai.jupyter
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/

# tasks:
#   - name: "install requirements"
#     command: |
#       pip install -U pip
#       pip install yapf
#       pip install -r requirements.txt
#       pyenv install 3.6.0
#       pyenv virtualenv 3.6.0 my-env
#       pyenv activate my-env
#       pip install --upgrade pip
#       pip install tensorflow==1.14
#       exit

# vscode:
#   extensions:
#     - ms-python.python
#     - esbenp.prettier-vscode
#     - ms-toolsai.jupyter


tasks:
  - name: "install requirements"
    command: |
      pip install -U pip
      pip install yapf
      pip install pytest
      pyenv install 3.6.0
      pyenv virtualenv 3.6.0 my-env
      pyenv activate my-env
      pip install --upgrade pip
      exit

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter
