
# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "install requirements"
    command: |
      pip install -U pip
      pip install yapf
      pip install -r requirements.txt
      wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
      { echo ${KEYCODE_ENTER}; echo "yes"; echo ${KEYCODE_ENTER}; echo "yes"; } | bash Anaconda3-2021.11-Linux-x86_64.sh -u > /dev/null
      source ~/.bashrc
      { echo "y"; } | conda create -n py37 python=3.7.0
      source activate py37
      pip install pytest
      pip install torch==1.3.0
      pip install prefetch-generator==1.0.3
      pip install tqdm==4.64.1
      pip install pytorch-transformers==1.2.0
      pip install cached-property==1.5.2
      pip install overrides==7.3.1
      pip install protobuf==3.20.0
      pip install tensorflow==1.15.0
      pip install pytorch-crf -i https://pypi.tuna.tsinghua.edu.cn/simple/

      

vscode:
  extensions:
    - ms-python.python
    - esbenp.prettier-vscode
    - ms-toolsai.jupyter


